name = "HerbSpecification"
uuid = "6d54aada-062f-46d8-85cf-a1ceaf058a06"
authors = ["Tilman Hinnerichs <t.r.hinnerichs@tudelft.nl>"]
version = "0.2.0"

[deps]
AutoHashEquals = "15f4f7f2-30c1-5605-9d31-71845cf9641f"

[compat]
AutoHashEquals = "2.1,2.2"
julia = "1.8"
